# Generated by Django 2.2 on 2021-08-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210808_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmcode',
            name='valid_until',
            field=models.DateTimeField(null=True),
        ),
    ]
